pydicom/pynetdicom

pynetdicom3/DULprovider.py, pynetdicom3/association.py, test/test_ae.py
#29 fixed by moving DUL start into assoc.run()
=> Fix for #29, refactor of Association.run()

README.rst, pynetdicom3/ACSEprovider.py, pynetdicom3/DIMSEprovider.py, pynetdicom3/DULprovider.py, pynetdicom3/PDU.py, pynetdicom3/SOPclass.py, pynetdicom3/applicationentity.py, pynetdicom3/apps/echoscp/echoscp.py, pynetdicom3/apps/findscp/findscp.py, pynetdicom3/apps/findscu/findscu.py, pynetdicom3/apps/getscp/getscp.py, pynetdicom3/apps/getscu/getscu.py, pynetdicom3/apps/movescp/movescp.py, pynetdicom3/apps/movescu/movescu.py, pynetdicom3/apps/storescp/storescp.py, pynetdicom3/apps/storescu/storescu.py, pynetdicom3/association.py, pynetdicom3/primitives.py, pynetdicom3/utils.py, test/run_all_tests.py, test/test_ae.py, test/test_dimse_c.py, test/test_pdu.py, test/test_pdu_items.py, test/test_primitives.py, test/test_sop.py
=> Improve handling of elements with ambiguous VR, code quality improvements.

pynetdicom3/acse.py, pynetdicom3/applicationentity.py, pynetdicom3/association.py, pynetdicom3/dimse.py, pynetdicom3/dul.py, pynetdicom3/fsm.py, pynetdicom3/timer.py, test/dummy_c_scp.py, test/test_ae.py, test/test_assoc.py, test/test_dimse_provider.py, test/test_dul.py, test/test_timer.py
=> Fix for DIMSE timeout not applying, refactor of DUL._socket_to_pdu

pynetdicom3/applicationentity.py
=> Re-add sleep during SCP while waiting for assoc

pynetdicom3/utils.py, test/test_utils.py
=> Fix private transfer syntaxes raising ValueError during assoc

pynetdicom3/applicationentity.py, pynetdicom3/dimse_primitives.py, pynetdicom3/pdu_primitives.py, pynetdicom3/utils.py
Changes to match the refactor of pydicom.uid
Closes #74
=> [WIP] Fixes for upstream UID changes #74

pynetdicom3/apps/storescp/storescp.py
log level and log config are unused
=> Remove unused arguments

pynetdicom3/__init__.py, pynetdicom3/association.py, pynetdicom3/dimse.py
Revert some sleep times to pre-Status update (#102).
Really need to find a better method for managing race conditions/CPU usage
=> [MRG] Revert sleep times

pynetdicom3/dimse.py, pynetdicom3/tests/heavy_workload_assoc.py
=> Fix for debug message relying on non-mandatory element

pynetdicom3/sop_class.py
In a generator, instantiation doesn't run any code so there's
nothing to check there; exceptions are thrown during iteration.
So we wrap it with an iterator that will notify us when errors are
coming.
No test...
=> Check exceptions in on_c_find during iteration

pynetdicom3/applicationentity.py, pynetdicom3/association.py, pynetdicom3/tests/test_ae.py, pynetdicom3/utils.py
=> [MRG] Fix require calling/called AET not working correctly

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> [MRG] Add initial contributing, issue and PR guides

pynetdicom3/__init__.py, pynetdicom3/acse.py, pynetdicom3/apps/getscu/getscu.py, pynetdicom3/apps/movescu/movescu.py, pynetdicom3/apps/storescp/storescp.py
Related to #171
movescu.py doesn't work when the move destination is the move requestor due to limitations with the current code architecture.
=> [MRG] Fix apps being broken for storage requests

README.rst, pynetdicom3/dimse.py, pynetdicom3/tests/dummy_c_scp.py, pynetdicom3/tests/test_dimse_msg.py, pynetdicom3/tests/test_service_qr.py, pynetdicom3/tests/test_service_storage.py
=> [MRG] Fix for upstream pydicom changes to elements with VR of AE

build_docs/circle/push_doc.sh
=> [WIP] Update CircleCI config to not build gh-pages commits

docs/user/concepts.rst, pynetdicom3/dimse_messages.py, pynetdicom3/dimse_primitives.py, pynetdicom3/service_class.py, pynetdicom3/sop_class.py, pynetdicom3/status.py, pynetdicom3/tests/test_ae.py
=> [MRG] Minor refactor, prep work for new service classes

README.rst, docs/index.rst, docs/substance_admin.rst, pynetdicom3/ae.py, pynetdicom3/association.py, pynetdicom3/service_class.py, pynetdicom3/sop_class.py, pynetdicom3/status.py, pynetdicom3/tests/dummy_c_scp.py, pynetdicom3/tests/test_assoc.py, pynetdicom3/tests/test_service_substance_admin.py, pynetdicom3/tests/test_sop.py
=> [MRG] Add support for Substance Administration service

README.rst, docs/index.rst, docs/non_patient_service_class.rst, pynetdicom3/__init__.py, pynetdicom3/ae.py, pynetdicom3/association.py, pynetdicom3/presentation.py, pynetdicom3/service_class.py, pynetdicom3/sop_class.py, pynetdicom3/status.py, pynetdicom3/tests/dummy_c_scp.py, pynetdicom3/tests/test_presentation.py, pynetdicom3/tests/test_service_non_patient.py, pynetdicom3/tests/test_sop.py
=> [WIP] Add support for Non Patient Object Service Class

README.rst, docs/color_palette_service_class.rst, docs/defined_procedure_service_class.rst, docs/hanging_protocol_service_class.rst, docs/implant_template_service_class.rst, docs/index.rst, pynetdicom3/ae.py, pynetdicom3/association.py, pynetdicom3/presentation.py, pynetdicom3/service_class.py, pynetdicom3/sop_class.py, pynetdicom3/status.py, pynetdicom3/tests/dummy_c_scp.py, pynetdicom3/tests/test_assoc.py, pynetdicom3/tests/test_presentation.py, pynetdicom3/tests/test_service_qr.py, pynetdicom3/tests/test_sop.py
Add support for the following service classes:
* Hanging Protocol QR
* Defined Procedure Protocol QR
* Color Palette QR
* Implant Template QR
=> [MRG] Add remaining DIMSE-C using service classes

requirements.txt
- exposes dependencies to developers and to GitHub dependency scanner
- fixes #221
=> [MRG] Added requirements.txt for pydicom dependency

docs/reference/presentation.rst, docs/user/ae.rst, pynetdicom3/presentation.py, pynetdicom3/tests/test_presentation.py, pynetdicom3/tests/test_service_qr.py
=> [MRG] Simplify presentation context list generation

docs/user/ae.rst, docs/user/association.rst, pynetdicom3/ae.py, pynetdicom3/association.py, pynetdicom3/pdu_primitives.py, pynetdicom3/tests/test_ae.py, pynetdicom3/tests/test_assoc.py, pynetdicom3/tests/test_primitives.py
=> [MRG] Add callback for user identity negotiation

pynetdicom3/dimse_primitives.py, pynetdicom3/tests/test_dimse_c.py, pynetdicom3/tests/test_dimse_n.py
=> [MRG] Genericise DIMSE primitive setters/getters

pynetdicom3/__init__.py, pynetdicom3/_version.py, pynetdicom3/tests/test_environment.py, setup.py
=> [MRG] Fix versioning

pynetdicom3/pdu_primitives.py, pynetdicom3/tests/test_primitives.py
=> [MRG] No longer raise exception if implementation class uid is invalid

pynetdicom3/dul.py
=> Add debugging output of raw received A-ASSOCIATE-AC data

pynetdicom3/pdu.py, pynetdicom3/pdu_items.py
`__len__` implementation moved to the base classes.
=> [WIP] Minor refactor of PDU and PDU item __len__

pynetdicom/acse.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_logging.py
Closes #20, closes #21, closes #22
=> [MRG] Improvements and fixes for ACSE logging

pynetdicom/_version.py, setup.py
=> [MRG] Update version and setup.py in preparation for release

docs/changelog/v1.1.0.rst, pynetdicom/ae.py, pynetdicom/presentation.py, pynetdicom/tests/dummy_c_scp.py, pynetdicom/tests/heavy_workload_scp.py, pynetdicom/tests/heavy_workload_scu.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_assoc.py
=> [MRG] Use less CPU when idling as SCP

docs/changelog/v1.1.0.rst, docs/release_notes.rst, pynetdicom/acse.py, pynetdicom/ae.py, pynetdicom/dimse_messages.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_dimse_msg.py
=> [MRG] Deprecate AE.quit() and handle a maximum PDU length of 0 correctly

README.rst, docs/user/ae.rst, docs/user/concepts.rst, docs/user/index.rst, docs/user/presentation.rst
=> [MRG] Add presentation context guide to docs

pynetdicom/tests/test_ae.py, pynetdicom/tests/test_utils.py, pynetdicom/utils.py
=> [MRG] Refactor validate_ae_title

docs/changelog/v1.1.0.rst, pynetdicom/dimse_messages.py, pynetdicom/tests/heavy_workload_assoc.py, pynetdicom/tests/heavy_workload_scp.py, pynetdicom/tests/heavy_workload_scu.py, pynetdicom/tests/test_dimse_msg.py
=> [MRG] Make DIMSEMessage thread-safe

docs/changelog/v1.1.0.rst, pynetdicom/acse.py, pynetdicom/ae.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_assoc.py
* `AE.require_called_aet` changed to requiring bool
* `AE.require_calling_aet` changed to requiring list of bytes
Closes #130, closes #184
=> [MRG] Change requirements for rejecting based on Calling/Called AET

pynetdicom/acse.py
=> [WIP] Don't log an error when connection refused

README.rst, docs/changelog/v1.2.0.rst, docs/release_notes.rst, pynetdicom/_version.py, pynetdicom/acse.py, pynetdicom/ae.py, pynetdicom/dimse_messages.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_dimse_msg.py
=> [WIP] Post-release changes

docs/changelog/v1.2.0.rst, docs/examples/storage.rst, pynetdicom/_config.py, pynetdicom/ae.py, pynetdicom/association.py, pynetdicom/service_class.py, pynetdicom/tests/dummy_c_scp.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_service_storage.py
=> [WIP] Add option to skip decoding datasets during C-STORE operations

README.rst, docs/changelog/v1.2.0.rst, pynetdicom/_config.py, pynetdicom/ae.py, pynetdicom/dimse.py, pynetdicom/fsm.py, pynetdicom/tests/heavy_workload.py, pynetdicom/tests/heavy_workload_scp.py, pynetdicom/tests/heavy_workload_scu.py, pynetdicom/tests/test_fsm.py, pynetdicom/transport.py
=> [MRG] Improve reliability of FSM unit tests

docs/changelog/v1.2.0.rst, pynetdicom/association.py, pynetdicom/dimse.py, pynetdicom/dul.py, pynetdicom/fsm.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_fsm.py, pynetdicom/tests/test_timer.py, pynetdicom/timer.py
=> [MRG] Fix network_timeout not working correctly

pynetdicom/dimse.py, pynetdicom/dimse_primitives.py, pynetdicom/presentation.py, pynetdicom/tests/heavy_workload_scp.py, pynetdicom/tests/test_dimse_c.py, pynetdicom/tests/test_dimse_provider.py, pynetdicom/tests/test_presentation.py, pynetdicom/utils.py
=> [MRG] Fix presentation context negotiation with no acceptor transfer syntax

docs/examples/qr_get.rst
fixing some errors in the example for Query/Retrieve Get
=> [MRG] Update qr_get.rst

docs/changelog/v1.2.0.rst, pynetdicom/_version.py, pynetdicom/acse.py, pynetdicom/ae.py, pynetdicom/pdu_items.py, pynetdicom/tests/test_fsm.py, pynetdicom/tests/test_presentation.py, pynetdicom/transport.py
=> [MRG] Fix role selection when requestor only specifies one role

docs/changelog/v1.2.0.rst, docs/reference/presentation.rst, docs/user/association.rst, docs/user/presentation.rst, pynetdicom/__init__.py, pynetdicom/presentation.py, pynetdicom/tests/test_presentation.py
=> [MRG] Add convenience function for creating Role Selection items

pynetdicom/acse.py
=> [MRG] Improve A-ASSOCIATE logging for contexts and role selection

pynetdicom/transport.py
=> [MRG] Fix data being resent if first attempt failed

docs/changelog/v1.3.0.rst, docs/user/presentation.rst, pynetdicom/service_class.py, pynetdicom/tests/test_logging.py, pynetdicom/tests/test_service_qr.py
=> [MRG] Iterate C-MOVE and C-GET sub-operations' Message ID

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, docs/user/concepts.rst, pynetdicom/_config.py, pynetdicom/dimse_primitives.py, pynetdicom/pdu_items.py, pynetdicom/pdu_primitives.py, pynetdicom/presentation.py, pynetdicom/tests/test_dimse_c.py, pynetdicom/tests/test_dimse_n.py, pynetdicom/tests/test_pdu_items.py, pynetdicom/tests/test_presentation.py, pynetdicom/tests/test_primitives.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_utils.py, pynetdicom/utils.py
=> [MRG] Refactor UID parameter handling

.github/ISSUE_TEMPLATE.md, docs/changelog/v1.3.0.rst, docs/examples/verification.rst, pynetdicom/__init__.py, pynetdicom/_handlers.py, pynetdicom/ae.py, pynetdicom/apps/echoscp/echoscp.py, pynetdicom/apps/echoscu/echoscu.py, pynetdicom/apps/findscp/findscp.py, pynetdicom/apps/findscu/findscu.py, pynetdicom/apps/getscp/getscp.py, pynetdicom/apps/getscu/getscu.py, pynetdicom/apps/movescp/movescp.py, pynetdicom/apps/movescu/movescu.py, pynetdicom/apps/storescp/storescp.py, pynetdicom/apps/storescu/storescu.py, pynetdicom/tests/test_logging.py
=> [MRG] Change default logging configuration

pynetdicom/_handlers.py, pynetdicom/dimse_primitives.py, pynetdicom/events.py, pynetdicom/tests/test_events.py
Add decoded dataset properties to ``Event`` for the DIMSE-N requests
=> [MRG] Add properties to Event for DIMSE-N request datasets

README.rst, docs/changelog/v1.3.0.rst, docs/examples/mpps.rst, docs/index.rst, docs/modality_performed_procedure_step.rst, docs/reference/events.rst, pynetdicom/_config.py, pynetdicom/_handlers.py, pynetdicom/ae.py, pynetdicom/association.py, pynetdicom/dimse_primitives.py, pynetdicom/events.py, pynetdicom/service_class_n.py, pynetdicom/sop_class.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_assoc_n.py, pynetdicom/tests/test_dimse_n.py, pynetdicom/tests/test_events.py, pynetdicom/tests/test_service_mpps.py, pynetdicom/tests/test_sop.py
Closes #56, closes #95
* Add support for MPPS
* Add `Event.attribute_identifiers` property for N-GET requests
* Fix `Unified Procedure Step` SOP Class variable names
=> [MRG] Add support for Modality Performed Procedure Step

docs/changelog/v1.3.0.rst, pynetdicom/association.py, pynetdicom/pdu_items.py, pynetdicom/tests/test_pdu_items.py, pynetdicom/tests/test_transport.py, pynetdicom/transport.py
=> [MRG] Fix memory leak in AssociationServer

README.rst, docs/storage_service_class.rst, pynetdicom/__init__.py, pynetdicom/_version.py, pynetdicom/ae.py, pynetdicom/association.py, pynetdicom/presentation.py
=> [MRG] Update version and docstrings

README.rst, docs/changelog/v1.4.0.rst, docs/index.rst, docs/protocol_approval_service_class.rst, pynetdicom/association.py, pynetdicom/service_class.py, pynetdicom/sop_class.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_sop.py
=> [MRG] Add support for Protocol Approval

docs/examples/qr_find.rst
copying the source code and running it raises indentation error
=> [MRG] Fix indentation error in example

README.rst, docs/changelog/v1.4.0.rst, docs/examples/basic_worklist.rst, docs/examples/qr_find.rst, docs/examples/qr_get.rst, docs/examples/qr_move.rst, docs/examples/relevant_patient.rst, pynetdicom/_handlers.py, pynetdicom/apps/findscu/findscu.py, pynetdicom/apps/getscu/getscu.py, pynetdicom/apps/movescu/movescu.py, pynetdicom/association.py, pynetdicom/tests/test_assoc.py
=> [MRG] Require query_model parameter and change to allow UIDs

docs/changelog/v1.4.0.rst, pynetdicom/_handlers.py, pynetdicom/events.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_dimse_provider.py, pynetdicom/tests/test_events.py, pynetdicom/tests/test_fsm.py, pynetdicom/tests/test_pdu.py, pynetdicom/tests/test_transport.py
Closes #353, adds `Event.event` and removes `Event.name` and `Event.description`
=> [MRG] Add event property to Event

pynetdicom/pdu_items.py, pynetdicom/pdu_primitives.py, pynetdicom/presentation.py, pynetdicom/service_class_n.py, pynetdicom/sop_class.py, pynetdicom/status.py, pynetdicom/tests/test_dsutils.py, pynetdicom/tests/test_presentation.py, pynetdicom/tests/test_sop.py
* More preparation work for the remaining DIMSE-N classes
* Fix warning about empty transfer syntax
=> [MRG] Add SOP classes and statuses for DIMSE N

pynetdicom/tests/test_transport.py
=> [MRG] Add functionality test for connection with TLS

docs/changelog/v1.4.0.rst, docs/user/ae.rst, docs/user/association.rst, pynetdicom/acse.py, pynetdicom/ae.py, pynetdicom/pdu_primitives.py, pynetdicom/tests/benchmark_script.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_transport.py, pynetdicom/transport.py
=> [MRG] Add ae_title and contexts kwargs to start_server()

docs/changelog/v1.4.0.rst, pynetdicom/dimse_primitives.py, pynetdicom/tests/test_dimse_c.py
=> [MRG] Ignore invalid Move Destination AET

pynetdicom/association.py, pynetdicom/tests/test_service_relevant_patient.py
Ensure the association reactor starts up again
=> [MRG] Fix up checkpoint resets

docs/changelog/v1.4.0.rst, pynetdicom/association.py, pynetdicom/dimse_primitives.py, pynetdicom/tests/parrot.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_fsm.py, pynetdicom/tests/test_service_n.py, pynetdicom/tests/test_service_non_patient.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_service_relevant_patient.py, pynetdicom/tests/test_service_storage.py, pynetdicom/tests/test_service_substance_admin.py
* Unifies acceptor behaviour across both modes (closes #345)
* Fixes race condition during A-RELEASE collision handling
=> [MRG] Unify association modes

pynetdicom/acse.py, pynetdicom/association.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_fsm.py
=> [MRG] Refactor ACSE

docs/changelog/index.rst, pynetdicom/_version.py, pynetdicom/association.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_fsm.py, pynetdicom/tests/test_service_n.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_service_relevant_patient.py, pynetdicom/tests/test_service_substance_admin.py
=> [MRG] Bump version, remove query_model key

docs/changelog/v1.5.0.rst, pynetdicom/association.py, pynetdicom/transport.py
=> [MRG] Fix server socket not closing properly

pynetdicom/_handlers.py, pynetdicom/ae.py, pynetdicom/association.py, pynetdicom/tests/test_transport.py
=> [MRG] Add Lock to AE, lock threads during logging handlers

docs/changelog/v1.5.0.rst, pynetdicom/ae.py, pynetdicom/dimse_messages.py, pynetdicom/tests/test_dimse_msg.py, pynetdicom/tests/test_dimse_provider.py, pynetdicom/tests/test_transport.py, pynetdicom/transport.py
=> [MRG] Improve robustness when getting local address

.travis.yml, build_tools/travis/install.sh
=> [MRG] Switch codecov report uploader

.codecov.yml, .travis.yml, build_tools/travis/install.sh
=> [WIP] Coverage reliability improvements

.codecov.yml, pynetdicom/_handlers.py
=> [MRG] Fix handler import

docs/changelog/v1.5.0.rst, docs/reference/config.rst, pynetdicom/_config.py, pynetdicom/dimse_primitives.py, pynetdicom/tests/test_dimse_c.py, pynetdicom/utils.py
=> [MRG] Add config option for using short AE titles in DIMSE messages

docs/changelog/v1.5.0.rst, docs/index.rst, pynetdicom/association.py, pynetdicom/pdu_primitives.py, pynetdicom/tests/test_assoc.py
=> [MRG] Check user hasn't sent reject or abort before negotiating

pynetdicom/apps/storescp/storescp.py
=> Improvements for storescp.py

docs/changelog/v1.5.0.rst, pynetdicom/pdu_primitives.py, pynetdicom/tests/test_primitives.py
Thanks to @mbauskar for the fix, closes #413, closes #414
=> [MRG] Fix Implementation Version Name not allowing 1 character name

.travis.yml, docs/changelog/v1.5.0.rst, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_environment.py, pynetdicom/tests/test_timer.py, setup.py
=> [MRG] Add support for Python 3.8

docs/changelog/v1.5.0.rst, pynetdicom/_handlers.py, pynetdicom/events.py, pynetdicom/tests/test_events.py
=> [MRG] Add Event.message_id

docs/changelog/v1.5.0.rst, pynetdicom/acse.py, pynetdicom/association.py, pynetdicom/dimse.py, pynetdicom/dul.py, pynetdicom/fsm.py, pynetdicom/service_class.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_service_n.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_service_relevant_patient.py, pynetdicom/tests/test_service_storage.py, pynetdicom/tests/test_service_substance_admin.py, pynetdicom/tests/test_service_verification.py
=> [MRG] Handle peer and event handler aborting during DIMSE exchange

docs/changelog/v1.5.0.rst, pynetdicom/apps/tests/test_movescu.py, pynetdicom/service_class.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_dimse_c.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_transport.py, pynetdicom/utils.py
=> [MRG] Stop QR Move associating if no sub-operations

docs/changelog/v1.5.0.rst, pynetdicom/ae.py, pynetdicom/association.py, pynetdicom/service_class.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_assoc.py
=> [MRG] Fix race condition in Association

docs/apps/keyword_pathing.rst, docs/examples/qr_move.rst, docs/examples/storage.rst, docs/reference/index.rst, docs/reference/init.rst, pynetdicom/__init__.py, pynetdicom/association.py, pynetdicom/events.py, pynetdicom/tests/benchmark_script.py
=> [MRG] Minor fixes and improvements

pynetdicom/apps/tests/test_common.py, pynetdicom/dimse_primitives.py, pynetdicom/tests/test_ae.py
=> [MRG] Fix warnings regarding invalid escape sequences and syntax warning

docs/changelog/v1.5.0.rst, pynetdicom/ae.py, pynetdicom/tests/test_ae.py, pynetdicom/transport.py
https://github.com/pydicom/pynetdicom/issues/452
=> [MRG] Add hooks for custom server implementations

docs/changelog/v1.5.0.rst, pynetdicom/ae.py
=> [MRG] Add hook for creating AssociationSocket

docs/changelog/v1.5.0.rst, docs/user/association.rst, pynetdicom/status.py, requirements.txt, setup.py
=> [MRG] Fix incorrect status

docs/changelog/v1.5.0.rst, docs/reference/status.rst, pynetdicom/status.py, pynetdicom/tests/test_service_storage.py, pynetdicom/tests/test_status.py
=> [MRG] Add Status convenience class

docs/changelog/v1.5.0.rst, pynetdicom/transport.py
=> [MRG] Add hook for creating and modifying Association

docs/changelog/v1.5.0.rst, pynetdicom/association.py, pynetdicom/tests/test_assoc.py
=> [MRG] Prefer exact matching context

docs/apps/echoscp.rst, docs/apps/echoscu.rst, docs/apps/findscu.rst, docs/apps/getscu.rst, docs/apps/index.rst, docs/apps/movescu.rst, docs/apps/storescp.rst, docs/apps/storescu.rst, docs/changelog/v1.5.0.rst, pynetdicom/__main__.py, pynetdicom/apps/echoscp/echoscp.py, pynetdicom/apps/echoscu/echoscu.py, pynetdicom/apps/findscu/findscu.py, pynetdicom/apps/getscu/getscu.py, pynetdicom/apps/movescu/movescu.py, pynetdicom/apps/storescp/storescp.py, pynetdicom/apps/storescu/storescu.py, pynetdicom/apps/tests/test_echoscp.py, pynetdicom/apps/tests/test_echoscu.py, pynetdicom/apps/tests/test_findscu.py, pynetdicom/apps/tests/test_getscu.py, pynetdicom/apps/tests/test_movescu.py, pynetdicom/apps/tests/test_storescp.py, pynetdicom/apps/tests/test_storescu.py, pynetdicom/tests/test_cli.py
=> [MRG] Add CLI interface for apps

pynetdicom/_handlers.py
=> [MRG] Add message source to ACSE PDU logging

README.rst, docs/apps/echoscp.rst, docs/apps/echoscu.rst, docs/apps/findscu.rst, docs/apps/getscu.rst, docs/apps/movescu.rst, docs/apps/storescp.rst, docs/apps/storescu.rst
=> [MRG] Update README

docs/apps/findscu.rst, docs/apps/getscu.rst, docs/apps/movescu.rst, pynetdicom/apps/findscu/findscu.py, pynetdicom/apps/getscu/getscu.py, pynetdicom/apps/movescu/movescu.py
=> [MRG] Add SOP Class Extended Negotiation to QR apps

docs/changelog/v1.5.0.rst, pynetdicom/_handlers.py, pynetdicom/service_class.py, pynetdicom/tests/test_service_qr.py
=> [MRG] Add ability to yield association kwargs with evt.EVT_C_MOVE handlers

.travis.yml, docs/changelog/index.rst, docs/changelog/v1.5.1.rst, docs/index.rst, pynetdicom/_version.py, setup.py
=> [MRG] Change pydicom version requirement

README.rst, docs/changelog/index.rst, docs/changelog/v1.5.1.rst, docs/index.rst
=> [MRG] Include v1.5.1 changes

README.rst, docs/changelog/index.rst, docs/changelog/v1.5.1.rst, docs/changelog/v1.5.2.rst, docs/index.rst, docs/reference/sop_classes.rst, pynetdicom/_version.py, pynetdicom/association.py, pynetdicom/tests/test_assoc.py
=> [MRG] Fix selection of presentation context when using UPS 

README.rst, docs/changelog/index.rst, docs/changelog/v1.5.1.rst, docs/changelog/v1.5.2.rst, docs/index.rst, docs/reference/sop_classes.rst, pynetdicom/association.py, pynetdicom/tests/test_assoc.py
=> [MRG] Include changes from v1.5.2

.github/workflows/pypi-deploy.yml, .github/workflows/pytest-builds.yml
=> [MRG] Add PyPi deployment workflow

build_tools/circle/build_doc.sh, docs/conf.py
=> [MRG] Add copy button to docs

pynetdicom/_handlers.py
Fixes unformatted log message.
=> [MRG] fix: missing f-string in C-STORE request log

pynetdicom/_handlers.py
I really like these logs, it looks like a lot of effort went into
matching the logs generated by other DICOM toolkits. I'd like to capture
them for my own purposes. Initially I just added a handler to the
pynetdicom logger but I found that it would be better if I could
selectively capture them per-association.
=> [MRG] feat: return log content from standard handlers

docs/changelog/index.rst, docs/changelog/v1.5.3.rst, docs/changelog/v2.0.0.rst, pynetdicom/_config.py, pynetdicom/_handlers.py, pynetdicom/dimse_messages.py, pynetdicom/dsutils.py, pynetdicom/events.py, pynetdicom/service_class.py, pynetdicom/tests/test_events.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_service_storage.py
=> [MRG] Fix Move Originator Message ID not being set correctly when Move SCP

pynetdicom/_handlers.py
Follow-up to https://github.com/pydicom/pynetdicom/pull/534: actually return log content in top-level public handlers.
=> [MRG] feat: return content from public pdu / dimse handlers

pynetdicom/_handlers.py, pynetdicom/tests/test_logging.py
Add a handler that can be used when needing to debug the raw PDU data sent or received
=> [MRG] Add debug handler for EVT_DATA_RECV and EVT_DATA_SENT

pynetdicom/tests/test_transport.py, pynetdicom/tests/utils.py, pynetdicom/transport.py
=> [MRG] Add utility to wait for socket binding

docs/changelog/v2.0.0.rst, pynetdicom/dimse_messages.py, pynetdicom/tests/encoded_dimse_msg.py, pynetdicom/tests/test_dimse_msg.py, pynetdicom/tests/test_dimse_provider.py
=> [MRG] Allow decoding commands with duplicate fields in command set

docs/changelog/index.rst, docs/changelog/v1.5.4.rst, pynetdicom/_version.py, pynetdicom/pdu.py, pynetdicom/pdu_primitives.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_primitives.py
=> [MRG] Handle reserved abort source

docs/changelog/v2.0.0.rst, pynetdicom/service_class.py, pynetdicom/tests/test_service_qr.py
=> [MRG] Fix C-FIND sending the pending identifier upon success

MANIFEST.in
=> [MRG] Add missing qrscp config file to MANIFEST.in

MANIFEST.in, docs/changelog/index.rst, docs/changelog/v1.5.6.rst, docs/index.rst, pynetdicom/_version.py, pynetdicom/apps/common.py
=> [WIP] Backport app fixes

.github/workflows/pytest-builds.yml, docs/changelog/v2.0.0.rst, pynetdicom/service_class.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_assoc_n.py, pynetdicom/tests/test_fsm.py, pynetdicom/tests/test_logging.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_transport.py
* Fix failure to remove Overlay Data, Audio Sample Data and Curve Data when running Composite Instance w/o Bulk Data SCP
* Fix pydicom deprecation warnings
* Ignore FSM test warnings
=> [MRG] Fix failure to remove repeating group bulk data elements

.github/workflows/pypi-deploy.yml
=> [MRG] Fix deploy workflow

docs/changelog/v2.0.0.rst, pynetdicom/acse.py, pynetdicom/ae.py, pynetdicom/apps/tests/test_echoscu.py, pynetdicom/apps/tests/test_findscu.py, pynetdicom/apps/tests/test_getscu.py, pynetdicom/apps/tests/test_movescu.py, pynetdicom/apps/tests/test_storescu.py, pynetdicom/association.py, pynetdicom/fsm.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_transport.py, pynetdicom/transport.py
https://github.com/pydicom/pynetdicom/issues/616
=> [MRG] feat: add transport connection timeout

pynetdicom/pdu.py, pynetdicom/pdu_items.py, pynetdicom/pdu_primitives.py, pynetdicom/tests/test_pdu.py, pynetdicom/tests/test_pdu_items.py, pynetdicom/tests/test_primitives.py
=> [MRG] Add more validation of status strings

docs/changelog/v2.0.0.rst, docs/reference/config.rst, docs/reference/utils.rst, pynetdicom/_config.py, pynetdicom/_handlers.py, pynetdicom/dimse_primitives.py, pynetdicom/pdu_items.py, pynetdicom/pdu_primitives.py, pynetdicom/presentation.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_pdu_items.py, pynetdicom/tests/test_presentation.py, pynetdicom/tests/test_utils.py, pynetdicom/utils.py
Closes #611 
* Allow customisation of the codecs used for PDU decoding
* Add context for use in converting and validating UID parameters
=> [MRG] Add customisation of PDU codecs

docs/changelog/v2.0.0.rst, docs/examples/qr_move.rst, docs/reference/config.rst, docs/reference/utils.rst, docs/user/ae.rst, docs/user/association.rst, pynetdicom/_config.py, pynetdicom/_handlers.py, pynetdicom/ae.py, pynetdicom/apps/getscu/getscu.py, pynetdicom/apps/qrscp/qrscp.py, pynetdicom/apps/tests/test_echoscu.py, pynetdicom/apps/tests/test_findscu.py, pynetdicom/apps/tests/test_getscu.py, pynetdicom/apps/tests/test_movescu.py, pynetdicom/apps/tests/test_qrscp_move.py, pynetdicom/apps/tests/test_storescu.py, pynetdicom/dimse_primitives.py, pynetdicom/service_class.py, pynetdicom/tests/test_service_non_patient.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_service_storage.py
=> [MRG] Update documentation and apps

docs/changelog/v2.0.0.rst, pynetdicom/association.py, pynetdicom/tests/test_assoc.py
Closes #535, make it easier to use `Association.send_c_cancel()`
=> [WIP] Make C-CANCEL requests easier

pynetdicom/dimse_messages.py
=> [MRG] __future__ not needed (Python >= 3.7)

pynetdicom/_handlers.py, pynetdicom/dimse_messages.py, pynetdicom/dimse_primitives.py, pynetdicom/dsutils.py, pynetdicom/events.py, pynetdicom/tests/test_dimse_msg.py, pynetdicom/tests/test_service_qr.py
=> [MRG] Typing fixes

pynetdicom/apps/common.py, pynetdicom/apps/findscu/findscu.py, pynetdicom/presentation.py, pynetdicom/utils.py
Fix some of these alerts:
https://lgtm.com/projects/g/pydicom/pynetdicom/?mode=list&severity=warning
=> [MRG] Fix LGTM warnings

.github/workflows/pr-linter.yml, docs/changelog/v2.0.0.rst, docs/reference/sop_classes.rst, pynetdicom/apps/tests/test_storescp.py, pynetdicom/presentation.py, pynetdicom/tests/test_presentation.py, pynetdicom/tests/test_utils.py
* Add tests for LGTM fixes
* Add workflow to check code is blackened
* Add new SOP classes to API reference
=> [MRG] Add tests for LGTM fixes

pynetdicom/_validators.py, pynetdicom/apps/common.py, pynetdicom/apps/echoscu/echoscu.py, pynetdicom/apps/findscu/findscu.py, pynetdicom/apps/getscu/getscu.py, pynetdicom/apps/movescu/movescu.py, pynetdicom/apps/qrscp/handlers.py, pynetdicom/apps/qrscp/qrscp.py, pynetdicom/apps/storescp/storescp.py, pynetdicom/dimse_messages.py, pynetdicom/dimse_primitives.py, pynetdicom/pdu.py, pynetdicom/pdu_items.py, pynetdicom/pdu_primitives.py, pynetdicom/transport.py, pynetdicom/utils.py, setup.py
Fix some of these alerts:
https://lgtm.com/projects/g/pydicom/pynetdicom/?mode=list&severity=recommendation
=> [MRG] Fix LGTM recommendations

docs/changelog/v2.0.0.rst, pynetdicom/__main__.py, pynetdicom/_globals.py, pynetdicom/_handlers.py, pynetdicom/ae.py, pynetdicom/apps/common.py, pynetdicom/apps/findscu/findscu.py, pynetdicom/apps/getscu/getscu.py, pynetdicom/apps/qrscp/db.py, pynetdicom/apps/qrscp/qrscp.py, pynetdicom/apps/storescu/storescu.py, pynetdicom/association.py, pynetdicom/dsutils.py, pynetdicom/dul.py, pynetdicom/presentation.py, pynetdicom/sop_class.py, pynetdicom/status.py, pynetdicom/tests/parrot.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_fsm.py, pynetdicom/tests/test_transport.py, pynetdicom/transport.py, pynetdicom/utils.py
* Closes #669, force garbage collection during polling to cleanup dead Association threads.
* Code cleanup
=> [WIP] Fix memory leak in AssociationServer

.github/workflows/pr-linter.yml, .github/workflows/pr-pytest-apps.yml, .github/workflows/pr-pytest.yml, .github/workflows/pr-typing.yml, docs/changelog/index.rst, docs/changelog/v2.0.1.rst, pynetdicom/_globals.py, pynetdicom/_version.py, pynetdicom/tests/test_transport.py, pynetdicom/transport.py
Reverts change to default bind, fix for T_CONNECT with address tuple
=> [MRG] Revert change to default bind address

pynetdicom/ae.py, pynetdicom/transport.py
=> [MRG] Fix docstrings after bind address reversion

.github/workflows/publish-pypi-deploy.yml, docs/index.rst, pynetdicom/ae.py, pynetdicom/transport.py
=> [MRG] Minor updates from master

docs/changelog/v1.2.0.rst, docs/tutorials/create_scp.rst, docs/user/ae.rst, docs/user/association.rst, pynetdicom/dul.py, pynetdicom/pdu.py
=> [MRG] Fix typos (repeated words)

docs/conf.py, pynetdicom/apps/qrscp/db.py, pynetdicom/apps/tests/test_qrscp_db.py, pynetdicom/apps/tests/test_qrscp_echo.py, pynetdicom/apps/tests/test_qrscp_find.py, pynetdicom/apps/tests/test_qrscp_get.py, pynetdicom/apps/tests/test_qrscp_move.py, pynetdicom/apps/tests/test_qrscp_store.py, pynetdicom/dimse_primitives.py, pynetdicom/sop_class.py, pynetdicom/tests/test_sop.py
* Ignore validation warnings when running app tests
=> [MRG] Test updates for pydicom upstream validation changes

docs/changelog/v2.1.0.rst, pynetdicom/apps/qrscp/db.py, pynetdicom/dimse_primitives.py, pynetdicom/events.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_assoc_n.py, pynetdicom/tests/test_dimse_n.py, pynetdicom/tests/test_events.py, pynetdicom/tests/test_pdu_items.py, pynetdicom/tests/test_primitives.py, pynetdicom/tests/test_validators.py
* Closes #757 
* Fixes for pydicom disallowing single values in a list (https://github.com/pydicom/pydicom/pull/1608)
* Silence warnings for invalid element values in tests
=> [MRG] Fixes for upstream pydicom changes

pynetdicom/apps/common.py
=> [MRG]If already setup the logger, do not call addHandler.

docs/changelog/v2.1.0.rst, pynetdicom/dimse.py, pynetdicom/dimse_messages.py, pynetdicom/dimse_primitives.py, pynetdicom/tests/test_service_storage.py
=> [MRG] Fix receiving chunked datasets

docs/changelog/index.rst, docs/changelog/v2.0.2.rst, docs/conf.py, docs/index.rst, pynetdicom/apps/qrscp/db.py, pynetdicom/apps/tests/test_qrscp_db.py, pynetdicom/dimse_messages.py, pynetdicom/dimse_primitives.py, pynetdicom/events.py, pynetdicom/sop_class.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_assoc_n.py, pynetdicom/tests/test_dimse_n.py, pynetdicom/tests/test_events.py, pynetdicom/tests/test_pdu_items.py, pynetdicom/tests/test_primitives.py, pynetdicom/tests/test_service_storage.py, pynetdicom/tests/test_validators.py
=> [MRG] Backport fix for receiving chunked datasets

pynetdicom/_version.py, pynetdicom/tests/test_dimse_n.py
=> [MRG] Fix test missed when updating for pydicom changes

.github/workflows/merge-pytest.yml, .github/workflows/merge-typing.yml, .github/workflows/pr-linter.yml, .github/workflows/pr-pytest-apps.yml, .github/workflows/pr-pytest.yml, .github/workflows/pr-typing.yml, .github/workflows/publish-pypi-deploy.yml, pynetdicom/fsm.py, pynetdicom/tests/test_assoc_user.py
* `python-version` should be a string, not a float
* update GitHub actions
* fix typos found by [codespell](https://github.com/codespell-project/codespell) that broke the linter
=> [MRG] Update CI

.github/workflows/merge-typing.yml, .github/workflows/pr-typing.yml, pynetdicom/_handlers.py, pynetdicom/_validators.py, pynetdicom/apps/findscu/findscu.py, pynetdicom/apps/getscu/getscu.py, pynetdicom/apps/movescu/movescu.py, pynetdicom/apps/qrscp/qrscp.py, pynetdicom/apps/storescu/storescu.py, pynetdicom/apps/tests/test_qrscp_db.py, pynetdicom/dimse_messages.py, pynetdicom/pdu_items.py, pynetdicom/tests/parrot.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_fsm.py, pynetdicom/tests/test_service_non_patient.py, pynetdicom/tests/test_service_qr.py, pynetdicom/tests/test_service_relevant_patient.py, pynetdicom/transport.py
- pydicom cannot be installed in development mode for typing to work correctly
=> Typing fixes

docs/changelog/v2.1.0.rst, pynetdicom/apps/common.py
- prevents attacks using relative file paths
- fixes #823
I don't know how to test this without a large overhead, as the code in question is only used in the application code and is generally not tested.
=> Sanitize filenames for non-conformant SOP Instance UIDs

docs/examples/qr_find.rst
Added query level table. 
Address #782
=> [MRG] Update qr_find.rst

.github/workflows/pr-linter.yml
added spelling exceptions for requestor and requestors (King's English) 
remove selection of F821 for flake8 given it is explicitly then ignored
Another bare minimum PR (factored out of the PR that contained several workflow fixes, docs fix, and poetry/pyproject.toml changes).  The intent is to change only "one thing" at a time in these smaller PRs, and then I will cancel the larger "tidy-up" PR, leaving the poetry/pyproject.toml changes in a separate PR that will be kept in draft status while it is debated and alternatives are reviewed.
#839
=> [MRG] update workflow to avoid obsolescent approach to output (variables)

.github/workflows/merge-pytest.yml, .github/workflows/pr-pytest.yml
=> [MRG] Switch to the newly released Python 3.12

README.rst
=> [MRG] Update README.rst to use main

docs/user/ae.rst
=> [MRG] Update user guide with note about bind_address socket re-use

.github/workflows/pr-pytest.yml, README.rst, docs/changelog/v3.0.0.rst, docs/reference/config.rst, docs/reference/transport.rst, docs/tutorials/create_scu.rst, docs/user/ae.rst, docs/user/association.rst, pynetdicom/_config.py, pynetdicom/_globals.py, pynetdicom/_handlers.py, pynetdicom/acse.py, pynetdicom/ae.py, pynetdicom/association.py, pynetdicom/fsm.py, pynetdicom/pdu_primitives.py, pynetdicom/tests/test_acse.py, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_assoc.py, pynetdicom/tests/test_assoc_user.py, pynetdicom/tests/test_dimse_provider.py, pynetdicom/tests/test_fsm.py, pynetdicom/tests/test_logging.py, pynetdicom/tests/test_primitives.py, pynetdicom/tests/test_transport.py, pynetdicom/transport.py
* Add support for IPv6
* Add `transport.AddressInformation` class
* Various related small changes.
* Closes #984
=> Add support for IPv6

3.0/index.html
=> Update version default in index.html

docs/examples/qr_get.rst, docs/examples/storage.rst, docs/tutorials/create_scp.rst, docs/user/ae.rst, docs/user/concepts_contexts.rst, docs/user/concepts_information_model.rst, docs/user/concepts_uids.rst, pynetdicom/association.py
Fixes broken links, closes #1018
=> Documentation fixes for the user guide and tutorials

build_tools/sphinx/github_link.py, pynetdicom/__init__.py, pynetdicom/transport.py
=> Fix broken source links in documentation

.github/workflows/merge-pytest.yml, .github/workflows/pr-pytest-apps.yml, .github/workflows/pr-pytest.yml, pynetdicom/tests/test_ae.py, pynetdicom/tests/test_assoc.py
Test fixes and triage intermittent Windows timer test failure
=> Ensure serial tests run serially, add debugging to timer test

docs/_static/switcher.json, docs/conf.py
Fixes the version switcher not showing the currently selected version
=> Fix switcher not showing current version

docs/_static/switcher.json, docs/conf.py
Fix the version switcher not showing the currently selected version.
=> Fix version switcher

docs/_static/switcher.json
Try matching only to major and minor versions.
=> Use major and minor with switcher
