- pynetdicom3/ACSEprovider.py
- pynetdicom3/DIMSEprovider.py
- pynetdicom3/PDU.py
- pynetdicom3/applicationentity.py
- pynetdicom3/apps/echoscp/echoscp.py
- pynetdicom3/apps/findscp/findscp.py
- pynetdicom3/apps/findscu/findscu.py
- pynetdicom3/apps/getscp/getscp.py
- pynetdicom3/apps/getscu/getscu.py
- pynetdicom3/apps/movescp/movescp.py
- pynetdicom3/apps/movescu/movescu.py
- pynetdicom3/apps/storescp/storescp.py
- pynetdicom3/apps/storescu/storescu.py
- pynetdicom3/primitives.py
- pynetdicom3/utils.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Prefer `format()` over string interpolation operator](https://www.quantifiedcode.com/app/issue_class/4ACGxFj1)
Issue details: [https://www.quantifiedcode.com/app/project/gh:scaramallion:pynetdicom3?groups=code_patterns/%3A4ACGxFj1](https://www.quantifiedcode.com/app/project/gh:scaramallion:pynetdicom3?groups=code_patterns/%3A4ACGxFj1)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality …
> Fix "Prefer `format()` over string interpolation operator" issue

- pynetdicom3/dimse_messages.py
Its cost was quadratic to the length of the input. The new code has a linear cost.
> Fix a performance problem in DIMEMessage._bytestream_to_pdv. 

- pynetdicom3/applicationentity.py
- pynetdicom3/benchmarks/bench_presentation.py
- pynetdicom3/pdu.py
- pynetdicom3/presentation.py
- pynetdicom3/tests/test_presentation.py
- pynetdicom3/utils.py
Preparation for the refactor of Presentation related services.
- SCP/SCU Role Selection negotiation not implemented in the new Presentation Service as the current pynetdicom3 implementtation is not actually conformant to the DICOM specification. It'll be added at a later point.
- The added PresentationService should be regarded as experimental and is part of ongoing work into the TransportService implementation/refactor and moving towards using gevent instead of Python threading.
> Add PresentationService, tests and benchmarks.

- pynetdicom3/sop_class.py
- pynetdicom3/tests/test_assoc.py
When on_c_find is empty, which is should be in case there are no results (user is not supposed to return 0x0000 Success code), code breaks. Now fixed.
> Fix empty find

- pynetdicom3/sop_class.py
The last find-result that was sent, was sent a second time, along with the `Success` (0x0000) Status, which should not have any dataset with it.
It's difficult to write a test for it, because `on_c_find` doesn't attempt to parse the datasets of non `Pending` responses, so we need something lower-level to catch this.
> Fixed sending last find-result twice.

- pynetdicom3/acse.py
- pynetdicom3/association.py
- pynetdicom3/utils.py
By DICOM spec, all requested PCs from ASSOC-RQ should appear in
ASSOC-AC, either as accepted as rejected. Previously only the accepted
ones were present.
> Make Presentation Contexts in ASSOC-AC conform to DICOM spec

- pynetdicom3/applicationentity.py
- pynetdicom3/apps/storescp/storescp.py
It will restrict the network interface to listen on. This is useful when one wants a server to accept
connections only from a certain set of hosts (e.g., local processes)
> Add parameter bind_addr to ApplicationEntity. 

- pynetdicom3/sop_class.py
From [DICOM Storage Classes UID Reference](https://www.dicomlibrary.com/dicom/sop/), we learn that 
'DigitalXRayImageProcessingStorage' should be '1.2.840.10008.5.1.4.1.1.1.1.1' instead of '1.2.840.10008.5.1.4.1.1.1.1.1.1' . Due to mismatch, pynetdicom will produce 'not found error' for  'DigitalXRayImageProcessingStorage' class.
> [MPG] Fix sop_class errors.

- docs/examples/display.rst
- docs/examples/qr_get.rst
- pynetdicom3/ae.py
- pynetdicom3/apps/findscu/findscu.py
- pynetdicom3/apps/getscu/getscu.py
- pynetdicom3/association.py
- pynetdicom3/dimse_messages.py
- pynetdicom3/dimse_primitives.py
- pynetdicom3/presentation.py
- pynetdicom3/sop_class.py
- pynetdicom3/tests/dummy_c_scp.py
- pynetdicom3/tests/dummy_n_scp.py
- pynetdicom3/tests/test_assoc.py
- pynetdicom3/tests/test_assoc_n.py
- pynetdicom3/tests/test_presentation.py
- pynetdicom3/tests/test_service_display.py
- pynetdicom3/tests/test_service_non_patient.py
- pynetdicom3/tests/test_service_qr.py
- pynetdicom3/tests/test_service_relevant_patient.py
- pynetdicom3/tests/test_service_storage.py
- pynetdicom3/tests/test_service_substance_admin.py
- pynetdicom3/tests/test_sop.py
* Fix being able to send datasets with unmatched transfer syntaxes (#206)
* Improve access methods for the presentation contexts available to an established association
* Better logging/exception messages when contexts aren't accepted or wrong mode
* Change `SOPClass` to inherit from `UID`
> [MRG] Fix sending datasets that don't match the presentation context

- pynetdicom3/association.py
- pynetdicom3/tests/test_ae.py
MAX_PDU=0 should mean unlimited PDU but the code was subtracting 7 from this and
getting into trouble with a negative PDU size.  This change makes MAX_PDU=0 set
an internal PDU size of 64K.
#193
> [MRG] Fixed handling of MAX_PDU=0

- docs/changelog/0.9.1.rst
- docs/user/association.rst
- pynetdicom3/ae.py
- pynetdicom3/association.py
- pynetdicom3/pdu_primitives.py
- pynetdicom3/presentation.py
- pynetdicom3/service_class.py
- pynetdicom3/tests/test_ae.py
- pynetdicom3/tests/test_assoc.py
- pynetdicom3/tests/test_primitives.py
- pynetdicom3/tests/test_service_storage.py
* Add support for SOP Class Extended Negotiation
* Add support for sending/receiving Asynchronous Operations Window Negotiation items, however asynchronous operations are not supported by pynetdicom.
* Add `Association` properties for retrieving extended negotiation item responses.
* `Association.user_identity_response`
* `Association.asynchronous_operations_response`
* `Association.sop_class_extended_response`
> [MRG] Add callbacks for SOP Class Extended Negotiation, Async Ops

- docs/changelog/v1.1.0.rst
- docs/user/ae.rst
- docs/user/presentation.rst
- pynetdicom/acse.py
- pynetdicom/ae.py
- pynetdicom/dul.py
- pynetdicom/fsm.py
- pynetdicom/tests/dummy_c_scp.py
- pynetdicom/tests/test_acse.py
- pynetdicom/tests/test_ae.py
- pynetdicom/tests/test_assoc.py
- pynetdicom/tests/test_fsm.py
* Improve unit test coverage (both functional and non-functional) of the FSM
* Fix bug in AA_7
* Change network_timeout default to 60 s
* Acceptor no longer aborts if no accepted presentation contexts
> [MRG] Improve unit test coverage for the finite state machine

- docs/changelog/v1.2.0.rst
- pynetdicom/association.py
- pynetdicom/dul.py
- pynetdicom/tests/test_fsm.py
Rather than using `time.sleep()` calls to give the DUL time to start up, use a `threading.Event()` so the DUL notifies the association when its ready.
> [MRG] Improve association startup time

- docs/examples/qr_move.rst
- pynetdicom/_handlers.py
- pynetdicom/events.py
- pynetdicom/tests/test_events.py
- pynetdicom/tests/test_service_qr.py
* Adds `Event.move_destination` property for C-MOVE requests
* Fix for QR Move example (closes #349)
> [MRG] Add Event.move_destination, fix example

- docs/changelog/v1.4.0.rst
- pynetdicom/association.py
When acting as the association acceptor there's a race condition between the reactor and the send_* methods when processing the response to the DIMSE request. In order to fix this a checkpoint is added to the reactor which enables it to be paused
> [MRG] Add checkpoint to association reactor

- docs/changelog/v1.4.0.rst
- pynetdicom/association.py
- pynetdicom/sop_class.py
- pynetdicom/tests/test_assoc_n.py
Allows the use of Meta SOP Classes with the `Association.send_n_*()` methods, as required by the Print Management service class
> [MRG] Add meta_uid keyword parameter to Association send_n_*() methods

- docs/_static/css/pynetdicom.css
- docs/conf.py
Fix the bottom padding on sub-lists, sphinx no longer builds its own copy of the source code (and link to sphinx built source code removed from API docs).
> Fix list style, remove sphinx built source code

- README.rst
- docs/changelog/v1.4.0.rst
- docs/examples/print.rst
- docs/index.rst
- docs/service_classes/modality_performed_procedure_step.rst
- docs/service_classes/print_management.rst
- docs/service_classes/rt_machine.rst
- docs/service_classes/storage_commitment.rst
- docs/service_classes/ups.rst
- docs/user/association.rst
- docs/user/events.rst
- pynetdicom/_handlers.py
- pynetdicom/_version.py
- pynetdicom/association.py
- pynetdicom/dimse.py
- pynetdicom/events.py
- pynetdicom/tests/test_events.py
- pynetdicom/tests/test_service_n.py
In theory this should mean both synchronous and asynchronous N-EVENT-REPORT requests are handled properly. In theory....
Related to #8, #319
> [MRG] Handle N-EVENT-REPORT service requests immediately

- docs/examples/qr_get.rst
Noticed this typo while trying out the examples.
When executed, it would crash with:
```AttributeError: 'str' object has no attribute 'is_notification'```
Making the handler a tuple fixes it.
> Typo in C_GET SCP example

- .coveragerc
- .travis.yml
- build_tools/travis/install.sh
* Add `.converagerc` file and simplify coverage command
* Uninstall `enum34` package when using Python 2.7
> [MRG] StopTravis adding enum support for Python 2.7

- pynetdicom/apps/common.py
Only a small fix that is only relevant for exception handling (and did thus probably not yet surface),
nevertheless, for consistency, it should be fixed.
> [MRG] Fix wrong name of used status variable

- pynetdicom/apps/common.py
In the default storage handler the warning that the output DICOM file already exists currently ignores the output_directory (if set). This pull request fixes this.
> [MRG] Fix file overwrite warning ignoring output_directory

- pynetdicom/apps/tests/test_echoscp.py
- pynetdicom/apps/tests/test_echoscu.py
- pynetdicom/apps/tests/test_findscu.py
- pynetdicom/apps/tests/test_getscu.py
- pynetdicom/apps/tests/test_movescu.py
- pynetdicom/apps/tests/test_qrscp_echo.py
- pynetdicom/apps/tests/test_qrscp_find.py
- pynetdicom/apps/tests/test_qrscp_get.py
- pynetdicom/apps/tests/test_qrscp_move.py
- pynetdicom/apps/tests/test_qrscp_store.py
- pynetdicom/apps/tests/test_storescp.py
- pynetdicom/apps/tests/test_storescu.py
First step towards running apps tests on Windows. On Windows, executables, such as python.exe has the '.exe' postfix. Searching for 'python' in path will therefore fail. Searching for 'python.exe' would work, but by using sys.executable directly, we avoid searching for python on the path alltogether.
Since this is an unit test change only, I do not intend to add tests for the change. I can't guarantee that all apps tests pass, because there are more remaining issues on the Windows platform.
> [MRG] Small improvements to Apps tests on Windows

- pynetdicom/association.py
This makes troubleshooting timeouts a bit easier.
> [MRG] feat: log when DUL idle timer expires

- docs/changelog/v2.0.0.rst
- pynetdicom/service_class.py
- pynetdicom/tests/test_assoc.py
- pynetdicom/tests/test_service_qr.py
* Closes #592, closes #577
* Return failure status if all Move or Get suboperations failed
* Don't include the SOP instance UIDs for suboperations that return warning status
* Add abort/release check during Find/Move/Get SCP handler operation
> [MRG] Fix QR SCP not returning correct status if all subops failed

- docs/changelog/index.rst
- docs/changelog/v1.5.7.rst
- docs/index.rst
- pynetdicom/service_class.py
- pynetdicom/tests/test_assoc.py
- pynetdicom/tests/test_service_qr.py
* Send failure response if all QR subops fail
* Send correct Move Originator Message ID
* Don't include warning SOP Instances in Failed SOP instance UID List
> [MRG] Backport for QR fixes

- mypy.ini
- pynetdicom/__init__.py
- pynetdicom/_handlers.py
- pynetdicom/acse.py
- pynetdicom/association.py
- pynetdicom/dimse.py
- pynetdicom/dimse_primitives.py
- pynetdicom/dul.py
- pynetdicom/events.py
- pynetdicom/fsm.py
- pynetdicom/pdu_primitives.py
- pynetdicom/sop_class.py
- pynetdicom/tests/parrot.py
- pynetdicom/tests/test_fsm.py
- pynetdicom/utils.py
* Type hints for event, fsm and _handlers
* Fixes for AA-7 and AA-8
> Add and update type hints

- docs/changelog/v2.0.0.rst
- pynetdicom/pdu.py
- pynetdicom/pdu_primitives.py
- pynetdicom/tests/test_primitives.py
Related to #633, handle invalid result, source and diagnostic parameters in the A_ASSOCIATE string methods.
> [MRG] Add better handling of invalid A-ASSOCIATE (RJ) parameters during ACSE negotiation

- docs/changelog/v2.0.0.rst
- pynetdicom/_config.py
- pynetdicom/association.py
- pynetdicom/tests/test_assoc_user.py
> [MRG] Fix ServiceUser's presentation context getters

- pynetdicom/tests/benchmark_script.py
Added benchmark for dcmtk scu/scp for comparison. Current benchmarks have pynetdicom only version but no dcmtk only version for a fair comparison.
Here are the benchmarks on my MBA M1:
```
$ python pynetdicom/tests/benchmark_script.py 
Use yappi (y/n:)
n
Which benchmark do you wish to run?
1. Storage SCU, 1000 datasets over 1 association
2. Storage SCU, 1 dataset per association over 1000 associations
3. Storage SCP, 1000 datasets over 1 association
4. Storage SCP, 1000 datasets over 1 association (write)
5. Storage SCP, 1000 datasets over 1 association (write fast)
6. Storage SCP, 1000 datasets over 1 association (write fastest)
7. Storage SCP, 1 dataset per association over 1000 associations
8. Storage SCP, 1000 datasets per association over 10 simultaneous associations
9. Storage …
```
> Add DCMTK only benchmark

- pynetdicom/events.py
I'm having a read through to see how viable an async based pynetdicom would be. Through my reading I saw this PR's typo.
Cheers :),
Simon
---
PS: After having a scan, I've realised it would be a gigantorian effort to make it async... and so... I think I may just go the wrapper route for now, similar to what @moloney did in https://github.com/moloney/dcm
> Fix import typo

- docs/changelog/v2.0.0.rst
- pynetdicom/apps/qrscp/qrscp.py
> [MRG] Fix qrscp --clean

- lgtm.yml
Disable false positives that cannot be fixed by LGTM, because their heuristic detects strings such "`id`" that are actually very common in DICOM, for example in "`UID`".
> [MRG] Work around LGTM errors: Clear-text logging of sensitive information

- docs/changelog/v2.0.0.rst
- pynetdicom/_globals.py
- pynetdicom/ae.py
- pynetdicom/tests/test_ae.py
- pynetdicom/tests/test_fsm.py
- pynetdicom/transport.py
> [MRG] Use localhost as the default bind address

- docs/changelog/v2.0.0.rst
- docs/reference/transport.rst
- pynetdicom/acse.py
- pynetdicom/dimse.py
- pynetdicom/dul.py
- pynetdicom/fsm.py
- pynetdicom/pdu.py
- pynetdicom/tests/parrot.py
- pynetdicom/tests/test_acse.py
- pynetdicom/tests/test_dul.py
- pynetdicom/tests/test_fsm.py
- pynetdicom/tests/test_transport.py
- pynetdicom/transport.py
* Closes #721
* Added `transport.T_CONNECT`
* `AssociationSocket.connect()` now takes a `T_CONNECT` primitive instead of an address tuple
* Removes `DULServiceProvider.primitive` and `DULServiceProvider.pdu`
* Improves FSM unit test reliability and efficiency
> [MRG] Refactor DUL to remove primitive and pdu attributes

- docs/changelog/v2.0.0.rst
- docs/reference/config.rst
- pynetdicom/_config.py
- pynetdicom/apps/echoscp/echoscp.py
- pynetdicom/apps/echoscu/echoscu.py
- pynetdicom/apps/findscu/findscu.py
- pynetdicom/apps/getscu/getscu.py
- pynetdicom/apps/movescu/movescu.py
- pynetdicom/apps/qrscp/qrscp.py
- pynetdicom/apps/storescp/storescp.py
- pynetdicom/apps/storescu/storescu.py
- pynetdicom/dul.py
- pynetdicom/fsm.py
- pynetdicom/tests/test_ae.py
- pynetdicom/tests/test_dul.py
- pynetdicom/tests/test_transport.py
- pynetdicom/transport.py
* Closes #538 
* Adds a check that the socket still exists before sending data
* Reverts DISALLOWED_ADDRESSES changes
> [MRG] Check socket still exists before sending data

- docs/changelog/v2.0.0.rst
- pynetdicom/association.py
- pynetdicom/dul.py
- pynetdicom/fsm.py
- pynetdicom/tests/test_assoc.py
* Closes #619 
* Add `Association.network_timeout_response` to allow A-RELEASE instead of A-BORT
> [MRG] Allow A-RELEASE instead of A-ABORT on network timeout

- .github/workflows/publish-pypi-deploy.yml
- docs/changelog/index.rst
- docs/changelog/v2.0.1.rst
- docs/index.rst
- pynetdicom/_globals.py
- pynetdicom/tests/test_transport.py
- pynetdicom/transport.py
* Closes #728 
* Don't allow `T_CONNECT` initialisation using an address tuple
* Revert default bind address back to `("", 0)`
> [MRG] Don't allow address tuple for T_CONNECT initialisation

- docs/changelog/v2.1.0.rst
- pynetdicom/_config.py
- pynetdicom/pdu.py
- pynetdicom/tests/test_pdu.py
* Related to #746 
* Don't test reserved A-ASSOCIATE-AC values
* Doc fix for `_config.VALIDATORS`
> [MRG] Stop testing reserved A-ASSOCIATE-AC values

- pynetdicom/tests/test_assoc_user.py
- pynetdicom/tests/test_presentation.py
In Python 3.11, the messages associated with some `AttributeErrors` have changed. Adjust the message patterns in affected tests to accommodate both new and old message styles.
See #753 for details.
Fixes #753.
> [MRG] Fix AttributeError tests for Python 3.11

- pynetdicom/tests/test_utils.py
Fixes #755, test failures on `s390x`.
The test byte string on little-endian hosts is the same as it was before this commit: `b'\xff\xfe\x00\x001\x00\x00\x00.\x00\x00\x002\x00\x00\x00.\x00\x00\x003\x00\x00\x00'`.
On big-endian hosts, the test byte string now matches the one used on little-endian hosts, which makes the nature and message of the exception being tested endianness-independent.
Fixes #755.
> [MRG] Make decoding error tests endian-independent

- docs/changelog/v2.1.0.rst
- pynetdicom/apps/qrscp/db.py
- pynetdicom/apps/tests/test_qrscp_db.py
Small change in qrscp app (and related tests) to update the maximum length of `PatientID`.
#785
> [MRG] Set correct max length for PatientID attribute in qrscp

- docs/conf.py
update caption to specify "#%s" rather than "#". The latter worked in Sphinx 5.3.0, warned in 6.x, fails in 7.x
This is a bare minimum PR.
Sphinx and sphinx-rtd-theme have a very delicate interplay in terms of versioning (otherwise there is a "style" error), so it's very important that those be updated in compatible fashion (hence using poetry and pyproject.toml... which is not included in this PR so that at least docs will build correctly in CircleCI and we can separate the two topics)
#839
> [MRG] Fix ext link doc formatting, sphinx obsolescence 

- .github/workflows/merge-pytest.yml
- .github/workflows/pr-pytest.yml
- docs/changelog/v2.1.0.rst
- pynetdicom/tests/hide_modules.py
- pynetdicom/tests/test_environment.py
Remove deprecated importlib.abc.Finder
#851
> [MRG] Update hide_modules.py

- pynetdicom/apps/common.py
- pynetdicom/dul.py
- pynetdicom/tests/parrot.py
- pynetdicom/tests/test_fsm.py
- pynetdicom/tests/test_transport.py
- pynetdicom/transport.py
* [`IOError` → `OSError`](https://docs.python.org/3/library/exceptions.html#IOError)
* [`socket.error` → `OSError`](https://docs.python.org/3/library/socket.html#socket.error)
* [`socket.timeout` → `TimeoutError`](https://docs.python.org/3/library/socket.html#socket.timeout)
> [MRG] Replace deprecated aliases of exceptions

- pynetdicom/service_class.py
Casting to `str` is redundant, it is the default.
From [Format Specification Mini-Language](https://docs.python.org/3/library/string.html#format-specification-mini-language):
> A general convention is that an empty format specification produces the same result as if you had called [`str()`](https://docs.python.org/3/library/stdtypes.html#str) on the value. A non-empty format specification typically modifies the result.
> [MRG] `{str(x)}` → `{x}`

- CONTRIBUTING.md
- README.rst
- asv.conf.json
- docs/conf.py
- docs/index.rst
- pynetdicom/apps/tests/test_common.py
> [MRG] http:// → https://

- pynetdicom/pdu_items.py
> [MRG] Use list comprehension

- .github/dependabot.yml
Actually automatically create a pull request.
> [MRG] Automatically update GitHub Actions

- .circleci/config.yml
- docs/changelog/index.rst
- docs/changelog/v2.2.0.rst
- docs/index.rst
- docs/reference/service_classes.rst
- docs/reference/sop_classes.rst
- docs/tutorials/index.rst
- docs/tutorials/register_sop_class.rst
- pynetdicom/__init__.py
- pynetdicom/service_class.py
- pynetdicom/sop_class.py
- pynetdicom/tests/test_service_qr.py
- pynetdicom/tests/test_service_storage.py
- pynetdicom/tests/test_service_substance_admin.py
- pynetdicom/tests/test_sop.py
* Makes registering new UIDs more obvious by adding a `register_uid()` function
* Closes #799
> [MRG] Make registering new UIDs easier

- pynetdicom/tests/test_fsm.py
> [MRG] Fixes for intermittent FSM test failures

- docs/changelog/v2.1.0.rst
- docs/examples/storage.rst
- docs/tutorials/create_scp.rst
- pynetdicom/apps/common.py
- pynetdicom/dsutils.py
- pynetdicom/events.py
- pynetdicom/tests/test_events.py
Adds a convenience function for accessing the encoded dataset and file meta
> [MRG] Add convenience function Event.encoded_dataset()

- .github/workflows/pr-pytest-apps.yml
- .github/workflows/pr-pytest.yml
- docs/changelog/v2.1.0.rst
- pynetdicom/ae.py
- pynetdicom/tests/test_transport.py
- pynetdicom/transport.py
- pyproject.toml
Add support for TLS v1.3, closes #364. This was waaaaay easier than I thought it was going to be.
> [MRG] Add support for TLS v1.3

- docs/changelog/v2.1.0.rst
- pynetdicom/ae.py
- pynetdicom/association.py
- pynetdicom/tests/test_assoc.py
Check for a mismatch between transfer syntax and dataset encoding and either try to fix it or raise if unable to. Closes #891
> [MRG] Check for encoding mismatch with send_c_store()

- docs/changelog/v2.1.0.rst
- pynetdicom/association.py
- pynetdicom/service_class.py
- pynetdicom/tests/test_assoc.py
> [MRG] Fix LOG_REQUEST_IDENTIFIERS not applying to Associaton send QR methods

- README.rst
- docs/Makefile
- docs/fix_search.py
- docs/make.bat
- pyproject.toml
> [MRG] Add fix for search not working

- pynetdicom/__main__.py
- pynetdicom/apps/echoscp/echoscp.py
- pynetdicom/apps/echoscu/echoscu.py
- pynetdicom/apps/findscu/findscu.py
- pynetdicom/apps/getscu/getscu.py
- pynetdicom/apps/movescu/movescu.py
- pynetdicom/apps/qrscp/qrscp.py
- pynetdicom/apps/storescp/storescp.py
- pynetdicom/apps/storescu/storescu.py
There's no need to do this since argparse can accept a list of arguments, and it doesn't seem like a good idea to overwrite the list of arguments provided.
N/A
> Remove the overwriting of sys.argv

- pynetdicom/association.py
- pynetdicom/dsutils.py
- pynetdicom/events.py
- pynetdicom/tests/test_assoc.py
- pynetdicom/tests/test_dsutils.py
- pyproject.toml
Support for pydicom v3, but drops support for pydicom v2.
> [MRG] Support for pydicom v3

- .github/workflows/merge-pytest.yml
- .github/workflows/pr-pytest.yml
- docs/changelog/v2.2.0.rst
- docs/examples/qr_get.rst
- docs/examples/qr_move.rst
- docs/service_classes/query_retrieve_service_class.rst
- pynetdicom/service_class.py
- pynetdicom/tests/test_service_qr.py
- pyproject.toml
> [WIP] Limit C-MOVE and C-GET to 65535 suboperations

- docs/changelog/v3.0.0.rst
- pynetdicom/_handlers.py
- pynetdicom/service_class.py
- pynetdicom/tests/test_service_n.py
* Add a way to set *Affected SOP Instance UID* in an N-CREATE-RSP when absent from the -RQ (closes #995)
* Add default debugging handlers for the remaining DIMSE-N messages
> Add a method to set Affected SOP Instance UID for N-CREATE-RSP

- docs/changelog/v3.0.0.rst
- pynetdicom/acse.py
- pynetdicom/association.py
- pynetdicom/dimse_messages.py
- pynetdicom/dul.py
- pynetdicom/fsm.py
- pynetdicom/tests/encoded_pdu_items.py
- pynetdicom/tests/parrot.py
- pynetdicom/tests/test_acse.py
* Change FSM to put P-DATA PDUs into the DIMSE queue instead of the `to_user_queue`
* Add `Association._sent_release` flag that is set once association release beings
* Change `Association._serve_request()` to return early if `_sent_release` flag is set
* Add warning to logging if P-DATA received during association release
* Closes #820
> Improvements for handling P-DATA received during association release

- docs/changelog/v3.0.0.rst
- pynetdicom/association.py
- pynetdicom/fsm.py
- pynetdicom/transport.py
* Add redundancy to ensure socket shutdown/close during abort and connection failure
* Closes #979
> Add redundancy to ensure sockets are closed after an association ends

- docs/changelog/v3.0.0.rst
- pynetdicom/transport.py
* An `AttributeError` exception during AA-7 was occurring because the socket got reset before the A-ABORT PDU could be sent.
* Closes #806
> Catch socket deallocation exception during AA-7

- docs/changelog/v3.1.0.rst
- pynetdicom/tests/test_transport.py
- pynetdicom/transport.py
When using a hostname instead of an IP-address, the AddressInformation.address_family function would return AF_INET6. This doesn't work in an environment without IPv6 such as in (some) Docker containers.
Furthermore, a (rather hypothetical) scenario where IPv4 is not available was not supported.
To fix these issues, AddressInformation.address now does DNS lookup. This means that the address_family/is_ipv4/is_ipv6 functions now work as intended. IPv4 address are preferred over IPv6 for compatibility.
> Fix issue with using a hostname without IPv6

- docs/_static/switcher.json
- docs/conf.py
I can see myself on my deathbed, still trying to get this working properly.
The dropdown buttons use an equivalency match for 'version' value in switcher.JSON to the `version_match` attr in the conf.py file, BUT the warning banner uses a different method for matching based on [compare-versions](https://github.com/omichelsen/compare-versions), so one can match and the other not. I think the solution is to use MAJOR.MINOR.* (or MAJOR.MINOR.PATCH) in both switcher.json and conf.py, but we'll see.
> Use wildcard to fix warning banner

- pynetdicom/__init__.py
- pynetdicom/presentation.py
- pynetdicom/tests/test_presentation.py
* Register the missing public transfer syntaxes with pydicom - not that it'll be needed in the actual 3.1 release
* Add a test to ensure all transfer syntaxes in pynetdicom are registered with pydicom
* Remove a redundant transfer syntax check and warning
> Fix missing public transfer syntaxes

- docs/changelog/index.rst
- docs/changelog/v3.0.4.rst
- pynetdicom/__init__.py
- pynetdicom/presentation.py
- pynetdicom/tests/test_presentation.py
- pynetdicom/transport.py
- pyproject.toml
Fixes missing transfer syntax warnings
> Fix missing transfer syntax warnings
